version: '3.3'
services:
  pytest:
    build:
      context: ./api
    container_name: pytest
    networks:
      - backend
    env_file:
      - ./api_secrets.env
    command: ["pytest", "-v"]

networks:
  backend:
    driver: bridge

