version: '3.3'
services:
  db_mysql:
    restart: always
    build:
      context: ./databases
    container_name: db_mysql
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    env_file:
      - ./mysql_secrets.env
    
  api:
    restart: always
    build:
      context: ./api
    container_name: api
    networks:
        - backend
    env_file:
      - ./api_secrets.env
    environment:
      - TERM=xterm-256color
    ports:
      - "8000:8000"
    depends_on:
      - db_mysql

  db:
    restart: always
    image: postgres:13
    container_name: mlflow_db
    expose:
        - 5432
    networks:
        - backend
    env_file:
      - ./postgres_secrets.env
      - ./postgres.env
    volumes:
        - db_datapg:/var/lib/postgresql/data
        - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    restart: always
    build:
      context: ./mlflow
    image: mlflow_server
    container_name: mlflow_server
    expose:
        - 5001
    networks:
        - frontend
        - backend
    env_file:
        - ./app_secrets.env
        - ./app.env
    volumes:
        - mlrun_data:/mlruns
    command: 
        - sh
        - -c

# MLflow Tracking Server used exclusively as proxied access host for artifact storage access
        # - mlflow server
        #   --artifacts-destination $${ARTIFACTS}
        #   --host $${HOST_MLFLOW_IP}
        #   --port $${MLFLOW_PORT}
        #   --serve-artifacts

# MLflow Tracking Server enabled with proxied artifact storage access
        - mlflow server
            --port $${MLFLOW_PORT}
            --host $${HOST_MLFLOW_IP}
            --backend-store-uri $${BACKEND} 
            --default-artifact-root $${ARTIFACTS}Ò
            --serve-artifacts

    depends_on:
        - db

  nginx:
      restart: always
      build: ./nginx
      image: mlflow_nginx
      container_name: mlflow_nginx
      ports:
          - 5000:80
      networks:
          - frontend
      depends_on:
          - app

networks:
  frontend:
      driver: bridge
  backend:
      driver: bridge

volumes:
  db_datapg: {}
  mlrun_data: {}
  db_data: {}

